version: '3.8'

services:
  api:
    build: .
    container_name: visualiza-api-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
